repository: 경주현 컴퓨터 시스템 연구 노트

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: 경주현 컴퓨터 시스템 연구 노트 
# this appears on the top navigation bar next to the home button

site_title: 경주현 컴퓨터 시스템 연구 노트
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Kookmin Univ. 
# this appears in the footer

github_editme_path: joohyun0115/studies/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname: Joohyun Kyong
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - vendor/cache
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

#feedback_subject_line: kmu-sw git documentation 

#feedback_email: joohyun0115@kookmin.ac.kr
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

#collections:
#  tooltips:
#    output: true
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: studies_sidebar
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: os_sidebar
# these are defaults used for the frontmatter for these file types

sidebars:
- studies_sidebar
- os_sidebar
- other

description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."
# the description is used in the feed.xml file

# needed for sitemap.xml file only
url: http://idratherbewriting.com
